name: Log Date and Time

on:
  schedule:
    - cron: '*/30 * * * *'  # Changed from */5 to */30 minutes
  workflow_dispatch:        # Keep manual trigger option

jobs:
  log_datetime:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
     - name: Run logging script
        run: |
          chmod +x ./log_time.sh
          ./log_time.sh
      
      - name: Count log entries
        run: |
          chmod +x ./count_logs.sh
          ./count_logs.sh
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add logs/log.txt
          git commit -m "Update log with new timestamp" || echo "No changes to commit"
          git push
